### ISSUE TITLE
map has() crashes for non-existent keys

### ISSUE THREAD

**Issue by kevgug** [freestyle-sh/cloudstate#13]
## Example
```js
{
    const map = new Map([
        ["foo", 1],
        ["bar", 2],
        ["baz", 3],
    ]);

    const object = {
        value: map,
    };

    setRoot("test-root", object);
    commit();
}

{
    const object = getRoot("test-root");

    console.log("before");
    if (object.value.has("qux")) { // crashes here
        throw new Error(`Expected ${JSON.stringify("qux")} to not exist`);
    }
    console.log("after");
}
```

```
before
fatal runtime error: failed to initiate panic, error 5
```

**Comment by wasifkareem** [comment]
Hi @kevgug, I’m interested in contributing to this issue. Could you please provide more details? I’m excited about the idea behind Freestyle and would love to contribute.

**Comment by kevgug** [comment]
Hi @wasifkareem, thanks for your interest in contributing. I had self-assigned this issue but I'd love to refer you to our [CONTRIBUTING.md](https://github.com/freestyle-sh/cloudstate/blob/main/CONTRIBUTING.md) document. At the moment, writing JS tests for everything labelled "Not Tested" in [SUPPORT.md](https://github.com/freestyle-sh/cloudstate/blob/main/SUPPORT.md) is the quickest way to support us.
