### ISSUE TITLE
Missing Footer Section on Freestyle Website.

### ISSUE THREAD

**Issue by DeviSriSaiCharan** [freestyle-sh/cloudstate#20]
Hello Team,

I noticed that your Freestyle website doesn't have a footer section. Adding a footer section would enhance the user experience and make the site look more professional. Footers typically contain important elements such as:

- Navigation Links: Quick access to essential pages (e.g., documentation, blog, contact information).
- Contact and Social Media: Makes it easier for users to connect with the team or follow updates.
- Legal Information: Displaying copyright or terms of service, which is a standard practice and adds professionalism.
Would it be possible to include a footer section in a future update?

**Comment by martianshaan** [comment]
can I worked on this ?
